"""add external_id, title, change embedding to 768 dim

Revision ID: 74878a053f37
Revises: 3f02b23e342a
Create Date: 2026-09-15 17:40:39.698239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa 
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '74878a053f37'
down_revision: Union[str, Sequence[str], None] = '3f02b23e342a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunk', sa.Column('external_id', sa.String(length=128), nullable=False))
    op.add_column('knowledge_chunk', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('knowledge_chunk', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('knowledge_chunk', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=False)
    op.create_index(op.f('ix_knowledge_chunk_external_id'), 'knowledge_chunk', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunk_external_id'), table_name='knowledge_chunk')
    op.alter_column('knowledge_chunk', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=False)
    op.drop_column('knowledge_chunk', 'updated_at')
    op.drop_column('knowledge_chunk', 'title')
    op.drop_column('knowledge_chunk', 'external_id')
    # ### end Alembic commands ###
